<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{{ asset('template/administracion.js')}}"></script>
<script src="{{ asset('template/gestion.js')}}"></script>
<script src="{{ asset('template/perfiles.js')}}"></script>
<script src="{{ asset('template/procesos.js')}}"></script>
<script src="{{ asset('template/myscript.js')}}"></script>
<script src="{{ asset('template/paginacion.js')}}"></script>
<script src="{{ asset('js/upload.js')}}"></script>
<script src="{{ asset('template/bundles/libscripts.bundle.js')}}"></script>
<script src="{{ asset('template/bundles/vendorscripts.bundle.js')}}"></script>
<script src="{{ asset('template/bundles/chartist.bundle.js')}}"></script>
<script src="{{ asset('template/bundles/knob.bundle.js')}}"></script>
<script src="{{ asset('template/bundles/flotscripts.bundle.js')}}"></script>
<script src="{{ asset('template/bundles/mainscripts.bundle.js')}}"></script>
<script src="{{ asset('template/index.js')}}"></script>
<script src="{{ asset('template/index.js')}}"></script>
<script src="{{ asset('vendor/jquery-ui/jquery-ui.min.js')}}"></script>
<script src="{{ asset('vendor/ckeditor/ckeditor.js')}}"></script>
<script src="{{ asset('template/summernote/dist/summernote.js')}}"></script>
<script src="{{ asset('template/DataTables/datatables.min.js')}}"></script>
